name: baseline-ci-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ML workflow
          pip install -r requirements.txt
          python train/train.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish loss.png --md >> report.md
          cml-publish acc.png --md >> report.md
          
          cml-send-comment report.md 
